modLoader="javafml"

loaderVersion="${loader_version_range}"

license="MIT"

#issueTrackerURL=""

logoFile="logo.png"

[[mods]]

modId="arcanerefraction"

version="1.20.4-1.0"

displayName="Arcane Refraction"

#updateJSONURL=""

#displayURL=""

#credits=""

authors="N2H4"

#displayTest="MATCH_VERSION"

description='''Mod adding multiblock structures that help with farming and generating resources.'''

#[[mixins]]
#config="${mod_id}.mixins.json"

[[dependencies.${mod_id}]]
    modId="neoforge" #mandatory
    type="required" #mandatory
    versionRange="${neo_version_range}" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

#file="META-INF/accesstransformer.cfg"

#[features.${mod_id}]
#openGLVersion="[3.2,)"
